// app/layout.js
import "./globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-[#0B0A0A] text-[#0B0A0A] dark:text-white">
        <Header />
        {children}
      </body>
    </html>
  );
}
